#!/usr/bin/python

import sys
sys.path[0:0] = [
    '/home/pmaupin/projects/opensource/rst2pdf-0.93',
    '/home/pmaupin/projects/opensource/rst2pdf-0.93/eggs/Sphinx-1.3.1-py2.7.egg',
    '/home/pmaupin/projects/opensource/rst2pdf-0.93/eggs/docutils-0.12-py2.7.egg',
    '/home/pmaupin/projects/opensource/rst2pdf-0.93/eggs/reportlab-2.3-py2.7-linux-i686.egg',
    '/home/pmaupin/projects/opensource/rst2pdf-0.93/eggs/aafigure-0.5-py2.7.egg',
    '/home/pmaupin/projects/opensource/rst2pdf-0.93/eggs/nose-1.3.7-py2.7.egg',
    '/home/pmaupin/projects/opensource/rst2pdf-0.93/eggs/coverage-4.0a6-py2.7-linux-i686.egg',
    '/usr/lib/pymodules/python2.7',
    '/home/pmaupin/projects/opensource/rst2pdf-0.93/eggs/svg2rlg-0.3-py2.7.egg',
    '/home/pmaupin/projects/opensource/rst2pdf-0.93/eggs/sphinx_rtd_theme-0.1.8-py2.7.egg',
    '/home/pmaupin/projects/opensource/rst2pdf-0.93/eggs/alabaster-0.7.6-py2.7.egg',
    '/home/pmaupin/projects/opensource/rst2pdf-0.93/eggs/Babel-1.3-py2.7.egg',
    '/home/pmaupin/projects/opensource/rst2pdf-0.93/eggs/snowballstemmer-1.2.0-py2.7.egg',
    '/home/pmaupin/projects/opensource/rst2pdf-0.93/eggs/Pygments-2.0.2-py2.7.egg',
    '/home/pmaupin/projects/opensource/rst2pdf-0.93/eggs/Jinja2-2.7.3-py2.7.egg',
    '/home/pmaupin/projects/opensource/rst2pdf-0.93/eggs/six-1.9.0-py2.7.egg',
    '/home/pmaupin/projects/opensource/rst2pdf-0.93/eggs/pyPdf-1.13-py2.7.egg',
    '/home/pmaupin/projects/opensource/rst2pdf-0.93/eggs/setuptools-18.0.1-py2.7.egg',
    '/home/pmaupin/projects/opensource/rst2pdf-0.93/eggs/pytz-2015.4-py2.7.egg',
    '/home/pmaupin/projects/opensource/rst2pdf-0.93/eggs/MarkupSafe-0.23-py2.7-linux-i686.egg',
    ]


import rst2pdf.createpdf

if __name__ == '__main__':
    sys.exit(rst2pdf.createpdf.main())
